version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret123
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  app:
    build: .
    container_name: app
    restart: always
    environment:
      PORT: "3000"
      DB_HOST: mysql            # service name
      DB_PORT: "3306"
      DB_USER: appuser
      DB_PASSWORD: appsecret123
      DB_NAME: appdb
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"             # optional (for direct access/testing)
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:3000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"   # exposed for demo; HTTPS block is commented in nginx.conf
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Uncomment to mount demo certs if you add the HTTPS server block
      # - ./certs:/etc/ssl/demo:ro

volumes:
  db_data:
